### ISSUE TITLE
Fix Calculator logic

### ISSUE THREAD

**Issue by krebedev** [jonahunuafe/age-calculator-app-main#1]
Great job @jonahunuafe! The UI looks good. 

Here're a few improvements you can make:

1. Calculation errors: The `year`, `month`, and `day ` results seem to be wrong. To reproduce, input the following date of birth and hit the button: 24/09/1984 (date format: `DD MM YYYY`). This is the exact date on the design in your ReadMe file. So the result should be `38 years, 3 months, 26 days
2. Reset results: After a calculation, changing any of the input values should clear off the results.
3. Zero-based inputs: The input fields accept and process zero values to generate results. `0` should not be accepted as a valid day, month, or year for these calculations.

**Comment by jonahunuafe** [comment]
> Great job @jonahunuafe! The UI looks good.
> 
> Here're a few improvements you can make:
> 
> 1. Calculation errors: The `year`, `month`, and `day ` results seem to be wrong. To reproduce, input the following date of birth and hit the button: 24/09/1984 (date format: `DD MM YYYY`). This is the exact date on the design in your ReadMe file. So the result should be `38 years, 3 months, 26 days
> 2. Reset results: After a calculation, changing any of the input values should clear off the results.
> 3. Zero-based inputs: The input fields accept and process zero values to generate results. `0` should not be accepted as a valid day, month, or year for these calculations.

- Number one and number 3 conditions were met. For number 3, the years is 38 but the months were different due to difference in months when the project was on frontend mentor and when I did it. 
- I will work on the second one when am very good with Javascript. Thanks sir.

**Comment by jonahunuafe** [comment]
Thanks
